VKP-29-validation
frontend-park-mail-ru/2024_1_VKPogromisty pull request #11
Opened 2024-03-04 22:17 UTC by kond9

2024-03-06 18:41 UTC, CheerfulMushroom requested changes

2024-03-06 18:41 UTC, CheerfulMushroom commented on public/modules/validators.js
> +    if (password.length < 6) {
Надо это упростить всё до одной строки

2024-03-06 18:41 UTC, CheerfulMushroom commented on public/modules/validators.js
> +    if (password.length < 6) {
Относится ко всем валидаторам, которые так можно упростить

2024-03-06 18:41 UTC, CheerfulMushroom commented on public/modules/validators.js
> +export function validatePasswords(password, repeatPassword) {
Кажется, что конкретно этот валидатор слишком избыточен. Всё, что он делает это сравнивает 2 значения и никакой более сложной логики тут никогда не появится. Давайте от него избавимся

2024-03-06 18:41 UTC, CheerfulMushroom commented on public/sign_up.js
> +    const dateOfBirth = `${year.value}-${month.value.length === 1 ? '0' : ''}${month.value}-${day.value.length === 1 ? '0' : ''}${day.value}`;
Многа кода, сложна читать. Давайте упростим
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart

2024-03-06 18:41 UTC, CheerfulMushroom commented on public/sign_up.js
> +        console.log(result);
Выпиливаем все console.log'и

2024-03-06 18:41 UTC, CheerfulMushroom commented on public/modules/consts.js
> +export const responses = (ok, body, error) => {
Из названия непонятно, что именно здесь происходит. Обзовите её как-нибудь чем-нибудь более передающим суть типа genResponse

2024-03-06 18:41 UTC, CheerfulMushroom commented on public/modules/consts.js
> +export const responses = (ok, body, error) => {
Кажется, что эта функция используется только для апишных запросов в services.js и не будет использоваться нигде больше. Давайте её тогда туда и перенесём

2024-03-06 18:41 UTC, CheerfulMushroom commented on server/index.js
> +const PORT = 80;
Всё-таки локальную разработку на 80 порту вы вести не будете. Надо прокидывать номер порта в этот скрипт через переменные окружения

2024-03-06 18:41 UTC, CheerfulMushroom commented on public/modules/validators.js
> +export function validatePassword(password) {
JSDoc

2024-03-06 18:41 UTC, CheerfulMushroom commented on public/modules/services.js
>  export class AuthService {
JSDoc для классов и методов

2024-03-06 18:41 UTC, CheerfulMushroom commented on public/feed.js
> +for (let i of posts.body) {
Почему не const?

2024-03-06 18:41 UTC, CheerfulMushroom commented on public/feed.js
> +for (let i of posts.body) {
Дайте человекочитаемое имя для переменной. i, j, k используется для счётчиков обычно. У вас тут post больше подойдёт

2024-03-06 18:41 UTC, CheerfulMushroom commented on public/feed.js
> +    const post_header = createDivPost('post-header');
Надо всё в camelCase переводить

2024-03-06 18:41 UTC, CheerfulMushroom commented on public/feed.js
> +    for (let j of i.post.attachments) {
const + название переменной

2024-03-06 18:41 UTC, CheerfulMushroom commented on public/modules/validators.js
> +    if (name.match(/^[А-Яа-яA-Za-z]+$/) === null) {
В именах могут всречаться ещё пробелы, запятые, точки, дефисы
https://stackoverflow.com/questions/2385701/regular-expression-for-first-and-last-name

2024-03-06 18:41 UTC, CheerfulMushroom commented on public/modules/validators.js
> +    if (age > 120) {
Этот if избыточен

2024-03-06 18:41 UTC, CheerfulMushroom commented on public/sign_up.js
> +    if (!validateDateOfBirth(day.value, month.value, year.value)) {
Эта проверка никогда не пройдёт сейчас. Но почему я не скажу :)

2024-03-06 18:52 UTC, CheerfulMushroom requested changes

2024-03-06 18:52 UTC, CheerfulMushroom commented on public/index.html
>  </html>
Перенос строки в конец всех файлов

2024-03-06 18:56 UTC, CheerfulMushroom requested changes

2024-03-06 18:56 UTC, CheerfulMushroom commented on .eslintrc.json
В package.json нужен скрипт на запуск линтера

2024-03-06 18:56 UTC, CheerfulMushroom commented on .eslintrc.json
Нужно добавить автоматическую проверку файлов линтером перед коммитом
https://typicode.github.io/husky/get-started.html

2024-03-06 22:21 UTC, Famelbyby commented on public/feed.js
> +    const post_header = createDivPost('post-header');
Fixed

2024-03-06 22:22 UTC, Famelbyby commented on public/modules/validators.js
> +    if (name.match(/^[А-Яа-яA-Za-z]+$/) === null) {
Fixed

2024-03-06 22:23 UTC, Famelbyby commented on public/modules/validators.js
> +    if (age > 120) {
Fixed

2024-03-06 22:23 UTC, Famelbyby commented on public/modules/validators.js
> +export function validatePasswords(password, repeatPassword) {
Fixed

2024-03-06 22:24 UTC, Famelbyby commented on public/modules/validators.js
> +    if (password.length < 6) {
Fixed

2024-03-06 22:26 UTC, Famelbyby commented on public/sign_up.js
> +    const dateOfBirth = `${year.value}-${month.value.length === 1 ? '0' : ''}${month.value}-${day.value.length === 1 ? '0' : ''}${day.value}`;
Fixed

2024-03-06 22:29 UTC, Famelbyby commented on public/sign_up.js
> +        console.log(result);
Fixed

2024-03-06 22:30 UTC, Famelbyby commented on public/modules/consts.js
> +export const responses = (ok, body, error) => {
Fixed

2024-03-06 22:31 UTC, Famelbyby commented on public/modules/consts.js
> +export const responses = (ok, body, error) => {
Fixed

2024-03-06 22:47 UTC, Famelbyby commented on .eslintrc.json
Fixed

2024-03-06 22:51 UTC, Famelbyby commented on public/feed.js
> +for (let i of posts.body) {
Fixed

2024-03-06 22:51 UTC, Famelbyby commented on public/feed.js
> +for (let i of posts.body) {
Fixed

2024-03-06 22:51 UTC, Famelbyby commented on public/feed.js
> +    for (let j of i.post.attachments) {
Fixed

2024-03-06 23:02 UTC, Famelbyby commented on public/index.html
>  </html>
Fixed

2024-03-06 23:45 UTC, Famelbyby commented on .eslintrc.json
Fixed

2024-03-07 14:20 UTC, CheerfulMushroom requested changes

2024-03-07 14:20 UTC, CheerfulMushroom commented on .husky/pre-commit
Перед коммитом должен линтер прогоняться. Тестов у вас скорее всего не будет никаких в принципе

2024-03-07 14:20 UTC, CheerfulMushroom commented on public/components/Feed/feedHeader.precompiled.js
Всё, что компилируется из исходников не должно попадать в репозиторий. Все precompiled нужно в .gitignore и удалить из репы

2024-03-07 14:20 UTC, CheerfulMushroom commented on static/images/logo (1).png
Какое-то мутное изменение. Оно точно нужно?

2024-03-07 16:27 UTC, Petr09Mitin commented on .husky/pre-commit
Fixed

2024-03-07 16:28 UTC, Petr09Mitin commented on public/components/Feed/feedHeader.precompiled.js
Fixed

2024-03-07 16:28 UTC, Petr09Mitin commented on static/images/logo (1).png
Left unchanged

2024-03-07 17:35 UTC, CheerfulMushroom commented on server/index.js
> +const PORT = 80;
Вижу, что появился .env файл. Не уверен, что он нужен, как и dotenv
Достаточно, чтобы сервер запускался с нужным портом при вызове   
`PORT=8888 node server/index.js`

2024-03-07 17:38 UTC, CheerfulMushroom requested changes

2024-03-07 17:38 UTC, CheerfulMushroom commented on public/modules/validators.js
> +  if (
Этот if тоже можно упростить

2024-03-07 18:19 UTC, CheerfulMushroom requested changes

2024-03-07 18:19 UTC, CheerfulMushroom commented on .gitignore
> +package-lock.json
:/

2024-03-07 18:21 UTC, CheerfulMushroom requested changes

2024-03-07 18:21 UTC, CheerfulMushroom commented on package.json
> +    "compile:templates": "handlebars ./public/components/Login/login.hbs -f ./public/components/Login/loginForm.precompiled.js && handlebars ./public/components/Signup/signup.hbs -f ./public/componen
Этот скрипт однозначно как-то проще должен прописываться

2024-03-07 18:21 UTC, CheerfulMushroom commented on package.json
> +    "prepare": "node .husky/install.mjs",
Не забыть выпилить вместе с install.mjs

2024-03-07 18:25 UTC, CheerfulMushroom commented on package.json
> +    "compile:templates": "handlebars ./public/components/Login/login.hbs -f ./public/components/Login/loginForm.precompiled.js && handlebars ./public/components/Signup/signup.hbs -f ./public/componen
Хотя лан, я сходу не нашёл какого-то нормального варианта

2024-03-07 18:41 UTC, CheerfulMushroom requested changes

2024-03-07 18:41 UTC, CheerfulMushroom commented on public/modules/validators.js
> +    providedDate.getDate() != inDay ||
Нестрогие сравнения - это зло

2024-03-07 19:05 UTC, Petr09Mitin commented on package.json
> +    "prepare": "node .husky/install.mjs",
Fixed

2024-03-07 19:05 UTC, Petr09Mitin commented on .gitignore
> +package-lock.json
Fixed

2024-03-07 19:14 UTC, CheerfulMushroom approved these changes

2024-03-07 19:14 UTC, merged