VKP-40-Figma
frontend-park-mail-ru/2024_1_VKPogromisty pull request #15
Opened 2024-03-10 17:16 UTC by kond9

2024-03-10 17:39 UTC, CheerfulMushroom requested changes

2024-03-10 17:39 UTC, CheerfulMushroom commented on public/index.js
> +    if (currentPageUrl === "/signup"){
Если открыть http://localhost:3000/signup, то редиректит на логин. Проверка location отрабатывает неверно
![image](https://github.com/frontend-park-mail-ru/2024_1_VKPogromisty/assets/43929910/edf5b69e-15e8-45fb-99b0-1ad9b5a9e97d)

2024-03-10 17:39 UTC, CheerfulMushroom commented on public/index.js
>      document.getElementById("sign-in-button").addEventListener("click", () => {
Ошибка при открытии регистрации
![image](https://github.com/frontend-park-mail-ru/2024_1_VKPogromisty/assets/43929910/6555cf16-1825-44f0-b2d6-71a6ff9f7320)

2024-03-10 17:39 UTC, CheerfulMushroom commented on public/index.css
Увеличение размеров кнопки на ховер - плохой эффект, его в вебе нигде особо не используют. Думаю, стоит убрать и в дальнейшем вообще такие эффекты не применять. У них очень узкие кейсы использования

![image](https://github.com/frontend-park-mail-ru/2024_1_VKPogromisty/assets/43929910/4a88ee1f-fc9f-41e2-8630-0873ee053574)

2024-03-10 17:39 UTC, CheerfulMushroom commented on public/index.js
Нажатие на эту ссылку обновляет страницу

![image](https://github.com/frontend-park-mail-ru/2024_1_VKPogromisty/assets/43929910/8e3a83cb-4466-40c3-a4f5-29597d4b7616)

2024-03-10 17:39 UTC, CheerfulMushroom commented on public/components/Signup/signup.hbs
Сообщение об ошибке не в том месте
![image](https://github.com/frontend-park-mail-ru/2024_1_VKPogromisty/assets/43929910/929eaae8-395b-42aa-b9ce-c3ad1a4df467)

2024-03-10 17:39 UTC, CheerfulMushroom commented on public/components/Signup/signup.hbs
Хотелось бы, чтобы описание поля и само поле начинались с одного места
![image](https://github.com/frontend-park-mail-ru/2024_1_VKPogromisty/assets/43929910/7d5c9494-1583-4637-9e24-a824852d4302)

2024-03-10 17:39 UTC, CheerfulMushroom commented on public/components/Signup/signup.hbs
Тип такого. Не критично, но не очень красиво сейчас
![image](https://github.com/frontend-park-mail-ru/2024_1_VKPogromisty/assets/43929910/9ff05e4e-0586-4fa5-8d5b-3d5c08a31b8f)

2024-03-10 17:44 UTC, CheerfulMushroom requested changes

2024-03-10 17:44 UTC, CheerfulMushroom commented on public/components/Signup/signup.hbs
> +        <button type="button" class="button-sign-in" id="button-sign-up">
У меня на этой кнопке нет event listener'ов
![image](https://github.com/frontend-park-mail-ru/2024_1_VKPogromisty/assets/43929910/ad863f50-508f-4226-80ae-73bcf39fe3df)

2024-03-10 17:44 UTC, CheerfulMushroom commented on public/index.js
> +      event.preventDefault();
Это сломается

2024-03-10 17:44 UTC, CheerfulMushroom commented on public/index.js
> +      event.preventDefault();
Это сломается

2024-03-10 20:31 UTC, Petr09Mitin commented on public/index.js
> +    if (currentPageUrl === "/signup"){
Fixed

2024-03-10 20:31 UTC, Petr09Mitin commented on public/index.js
> +      event.preventDefault();
Fixed

2024-03-10 20:32 UTC, Petr09Mitin commented on public/index.js
> +      event.preventDefault();
Fixed

2024-03-11 10:47 UTC, CheerfulMushroom approved these changes

2024-03-11 10:48 UTC, merged