Vkp 62 routing
frontend-park-mail-ru/2024_1_VKPogromisty pull request #21
Opened 2024-03-26 18:26 UTC by Petr09Mitin

2024-03-26 20:27 UTC, CheerfulMushroom requested changes

2024-03-26 20:27 UTC, CheerfulMushroom commented on public/index.js
> +    prestart: [
Лишнее

2024-03-26 20:27 UTC, CheerfulMushroom commented on public/index.js
> +    poststart: [
Заменить на глобальный listener

2024-03-26 20:27 UTC, CheerfulMushroom commented on public/routes.js
> +        Object.keys(this.#config.paths).find((elem) => {
Упростить. Смотреть по регуляркам

2024-03-26 20:27 UTC, CheerfulMushroom commented on public/routes.js
> +        history.replaceState("", "", url);
Пока стоит pushState, а то из-за replace вообще истории не останется

2024-03-26 23:02 UTC, Famelbyby commented on public/routes.js
> +        history.replaceState("", "", url);
Исправлено

2024-03-26 23:02 UTC, Famelbyby commented on public/routes.js
> +        Object.keys(this.#config.paths).find((elem) => {
Исправлено

2024-03-26 23:02 UTC, Famelbyby commented on public/index.js
> +    poststart: [
Исправлено

2024-03-26 23:02 UTC, Famelbyby commented on public/index.js
> +    prestart: [
Исправлено

2024-03-27 10:08 UTC, CheerfulMushroom requested changes

2024-03-27 10:08 UTC, CheerfulMushroom commented on public/index.js
> +  var ownUserId;
var?

2024-03-27 10:08 UTC, CheerfulMushroom commented on public/index.js
> +  body
Эту логику стоит перенести в роутер, она к нему относится напрямую. Где-нибудь в конструкторе её добавлять

2024-03-27 10:08 UTC, CheerfulMushroom commented on public/index.js
> +    .addEventListener('click', (event) => {
По идее этот листенер будет перехватывать событие уже после того, как оно обработается таргетом, то есть уже поздно. Тебе нужно его перехватывать на этапе погружения, а не всплытия

https://learn.javascript.ru/bubbling-and-capturing

2024-03-27 10:08 UTC, CheerfulMushroom commented on public/routes.js
> +        this.#config.paths.forEach((elem, id) => {
Много лишнего кода, ужимай сильнее. Тебе нужно найти первый path, у которого регулярка отработает на url. Используй find

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

2024-03-27 10:08 UTC, CheerfulMushroom commented on public/routes.js
> +        history.pushState("", "", url);
Согласно доке первый аргумент должен быть объектом

https://developer.mozilla.org/en-US/docs/Web/API/History/pushState

2024-03-27 12:40 UTC, CheerfulMushroom requested changes

2024-03-27 12:40 UTC, CheerfulMushroom commented on public/routes.js
> +        const body = document.getElementsByTagName('body')[0];
Просто document.body

2024-03-27 12:40 UTC, CheerfulMushroom commented on .husky/pre-commit
> +
:/

2024-03-27 12:40 UTC, CheerfulMushroom commented on public/index.js
> +    console.log(friends)
Убирай логи

2024-03-27 12:40 UTC, CheerfulMushroom commented on public/index.js
> +    console.log(subscribers);
Тоже

2024-03-27 12:40 UTC, CheerfulMushroom commented on public/routes.js
> +        const slug = foundedUrl.path.exec(url)[1];
А чего за slug, что в нём лежат будет?

2024-03-27 12:47 UTC, Famelbyby commented on public/routes.js
> +        const slug = foundedUrl.path.exec(url)[1];
Например для /profile/2 будет 2, для /chat/5 - 5; в данном случае это userId

2024-03-27 16:43 UTC, CheerfulMushroom commented on public/routes.js
> +        const slug = foundedUrl.path.exec(url)[1];
Пока норм, но в дальнейшем может стрельнуть в случае ссылок с несколькими переменными. Например, /posts/1/images/3

Возможно, есть смысл возвращать просто результат выполнения exec и его уже дальше анализировать. Но это так, не подумать

2024-03-27 16:46 UTC, CheerfulMushroom requested changes
А теперь нужно прогнать всё через линтер и починить всё, на что он жалуется :)

2024-03-27 18:08 UTC, CheerfulMushroom approved these changes

2024-03-27 18:08 UTC, merged