VKP-77-signup: сделать регистрацию по MVC
frontend-park-mail-ru/2024_1_VKPogromisty pull request #25
Opened 2024-03-28 11:22 UTC by Famelbyby

2024-03-28 13:30 UTC, CheerfulMushroom requested changes

2024-03-28 13:30 UTC, CheerfulMushroom commented on public/components/Signup/SignupModel.js
> +      localStorage.setItem("avatar", avatar);
Зачем в localstorage сохранять?

2024-03-28 13:30 UTC, CheerfulMushroom commented on public/index.js
> +    const signupController = new SignupController(router);
Обычно контроллеры один раз в самом начале приложения создают. Всё равно больше одного на приложение не понадобится

2024-03-28 13:30 UTC, CheerfulMushroom commented on public/components/Signup/SignupController.js
> +  redirect(path) {
А зачем эта функция тут?

2024-03-28 13:30 UTC, CheerfulMushroom commented on public/components/Signup/SignupController.js
> +  redirect(path) {
Просто я вижу, она маленькая и используется только в одном месте выше. Кажется, что можно без неё обойтись

2024-03-28 13:30 UTC, CheerfulMushroom commented on public/components/Signup/SignupModel.js
> +class SignupModel {
Наследуйся от BaseModel

2024-03-28 13:30 UTC, CheerfulMushroom commented on public/components/Signup/SingupView.js
> +class SignupView {
Наследуйся от BaseView

2024-03-28 13:30 UTC, CheerfulMushroom commented on public/components/Signup/SingupView.js
> +    console.log(this.#eventBus);
лог

2024-03-28 13:30 UTC, CheerfulMushroom commented on public/components/Signup/SignupModel.js
> +    if (result.ok) {
Нужна обработка всех возможных статусов, а не только запрос прошёл/не прошёл. Например, пришло 500, а ты пользователю скажешь, что он не правильно что-то сделал

2024-03-28 13:30 UTC, CheerfulMushroom commented on public/components/Signup/SingupView.js
> +        return false;
А зачем она что-то возвращает?

2024-03-28 13:30 UTC, CheerfulMushroom commented on public/components/Signup/SingupView.js
> +  redirect(result) {
Хотелось бы чуть более говорящие названия для функций. Чтобы по названию было ясно, какой кейс она обрабатывает. Например handleSignupResult

2024-03-28 13:30 UTC, CheerfulMushroom commented on public/components/Signup/SignupController.js
> +const incomingEvents = ["signup", "redirectFeed", "signupAnswer"];
Немного по наименованию событий:
События по сути своей описывают что произошло, а не отдают команду на то, что нужно сделать. Предлагаю придерживаться такого стиля наименований.
То есть, например, не "редиректни меня на ленту" (redirectFeed), а "успешно зарегистрирвался" (signupSuccess)

2024-03-28 13:30 UTC, CheerfulMushroom commented on public/components/Signup/SignupController.js
> +const incomingEvents = ["signup", "redirectFeed", "signupAnswer"];
Тоже относится и к другим событиям

2024-03-28 13:30 UTC, CheerfulMushroom commented on public/index.js
> +    const signupController = new SignupController(router);
Ну и заодно можно будет от функции renderSignUp избавится и сразу коллбэк в конфиг роутера убрать

2024-03-28 13:30 UTC, CheerfulMushroom commented on public/components/Signup/SingupView.js
>    async isValidForm() {
Вроде await не осталось. Кажется, что async можно убрать

2024-03-28 13:30 UTC, CheerfulMushroom commented on public/components/Signup/SignupModel.js
> +    if (result.ok) {
В данном случае у вас есть следующие кейсы

- 200 - всё ок, регистрация успешна. Надо редиректнуть на ленту
- 400 - какие-то кривые данные, бэку они не нравятся. Надо сказать пользователю, что с его данными есть проблемы
- всё остальное - неожиданная ошибка. Пользователю надо сказать, чтопроизошла неожиданная проблема

2024-03-28 13:48 UTC, Famelbyby commented on public/components/Signup/SignupModel.js
> +      localStorage.setItem("avatar", avatar);
Раньше был смысл так делать, сейчас его нет)

2024-03-29 07:42 UTC, CheerfulMushroom requested changes

2024-03-29 07:42 UTC, CheerfulMushroom commented on public/components/Signup/SingupView.js
> +   * @param {boolean} result - Результат регистрации
Уже не boolean)

2024-03-29 07:42 UTC, CheerfulMushroom commented on public/components/Signup/SingupView.js
> +    switch(result) {
Вообще в идеальном мире обработка статуса должна остаться в модели. Статусов может быть много, кейсы могут быть разные (вдруг иногда в случае проблемы надо будет за другими данными сходить), вью будет расти, логика работы с данными будет размываться между вью и моделью.

Поэтому ответ сначала стоит полностью обработать в модели, а потом перевариваемый результат передать во вью.

2024-03-29 07:51 UTC, CheerfulMushroom commented on public/components/Signup/SignupController.js
> +    this.eventBus.addEventListener("signupSuccess", router.redirect.bind(router));
Делать сигнал, чтобы потом в роутер передать путь, звучит кривовато. 
**_Не прошу переделывать_** тут что-то, но прошу подумать, зачем так сделано, точно ли стоит так делать и есть ли решение получше

2024-03-29 15:58 UTC, CheerfulMushroom requested changes

2024-03-29 15:58 UTC, CheerfulMushroom commented on public/components/Signup/SignupModel.js
> +        throw new Error("Unexpected error");
Не, не throw. Пользователю же надо показать будет хотя бы в теории, что есть проблема, то есть event какой-то во вью надо будет прокинуть. Предлагаю 2 варианта:
1) Прокидывать не true/false, а какой-то объект, по которому вью само решит, что нужно показать (внимание: само сообщение для пользователя должно будет формрироваться внутри вью, не надо тут создавать сообщение для юзера)
2) Сделать отдельный эвент на неожиданную ошибку, который обрабатывать во вью

2024-03-29 18:30 UTC, CheerfulMushroom approved these changes

2024-03-29 18:30 UTC, merged