VKP 78 login
frontend-park-mail-ru/2024_1_VKPogromisty pull request #26
Opened 2024-03-28 22:51 UTC by kond9

2024-03-29 07:59 UTC, CheerfulMushroom requested changes

2024-03-29 07:59 UTC, CheerfulMushroom commented on public/index.js
> +  const LoginController = new LoginController(router);
С большой буквы только классы называют, а не переменные

2024-03-29 07:59 UTC, CheerfulMushroom commented on public/components/Login/LoginModel.js
> +    this.eventBus.emit("loginAnswer", result.ok);
До этого места не дойдёт выполнение. Можешь проверить, что у тебя код работает, или бэк не вышло поднять локально?

2024-03-29 07:59 UTC, CheerfulMushroom commented on public/components/Login/LoginController.js
> +    this.eventBus.addEventListener(
Делать сигнал, чтобы потом в роутер передать путь, звучит кривовато. 
**_Не прошу переделывать_** тут что-то, но прошу подумать, зачем так сделано, точно ли стоит так делать и есть ли решение получше

2024-03-29 07:59 UTC, CheerfulMushroom commented on public/components/Login/ LoginView.js
У файла пробел в названии или мне кажется?

2024-03-29 07:59 UTC, CheerfulMushroom commented on public/components/Login/ LoginView.js
> +  async isValidForm() {
Где используется эта функция и почему она async?

2024-03-29 07:59 UTC, CheerfulMushroom commented on public/components/Login/ LoginView.js
> +    switch (result) {
Вообще в идеальном мире обработка статуса должна остаться в модели. Статусов может быть много, кейсы могут быть разные (вдруг иногда в случае проблемы надо будет за другими данными сходить), вью будет расти, логика работы с данными будет размываться между вью и моделью.

Поэтому ответ сначала стоит полностью обработать в модели, а потом перевариваемый результат передать во вью.

2024-03-29 07:59 UTC, CheerfulMushroom commented on public/components/Login/LoginModel.js
> +    this.eventBus.emit("loginAnswer", result.ok);
Если проблемы с поднятием бэка, то нужно будет сейчас взяться за задачу с походами в бэк прода и потом вернуться к этой

2024-03-31 17:50 UTC, CheerfulMushroom requested changes

2024-03-31 17:50 UTC, CheerfulMushroom commented on public/components/Login/LoginView.js
> +        await this.isValidForm();
Почему await?

2024-03-31 17:50 UTC, CheerfulMushroom commented on public/components/Login/LoginView.js
> +  isValidForm() {
Название функции не соответствует тому, что она делает. Обычно все функции, которые начинаются с is возвращают boolean и не делают какой-то логики. Тут же происходит и проверка, и модификация формы (логика отображения), и отправка сигнала в модель (считай поход в апи). 
Более говорящим названием для этой функции будет что-то типа checkAndSubmitForm

2024-03-31 17:50 UTC, CheerfulMushroom commented on public/components/Login/LoginView.js
> +const correct = "form__input__correct";
Какое-то более говорящее название для переменной хочется

2024-03-31 17:50 UTC, CheerfulMushroom commented on package.json
> +    "compile:templates": "handlebars ./public/components/Login/login.hbs -f ./public/components/Login/loginForm.precompiled.js && handlebars ./public/components/Signup/signup.hbs -f ./public/componen
Можешь эту команду в отдельный баш скрипт перенести? А то package.json слишком большой становится

2024-03-31 18:14 UTC, CheerfulMushroom commented on public/components/Login/LoginView.js
> +const correct = "form__input__correct";
Иногда ещё глобальные константы для файла заглавными буквами пишут. Так сразу в коде понятно, что это переменная на самом деле константа и она одинаковая на весь файл

2024-03-31 20:41 UTC, kond9 commented on public/components/Login/LoginView.js
> +        await this.isValidForm();
так чтобы оно параллельно выполнялось, разве нет? зачем нам ждать

2024-04-01 18:53 UTC, CheerfulMushroom requested changes

2024-04-01 18:53 UTC, CheerfulMushroom commented on compileTemplates.sh
Проверь, что скрипт работает, выглядит сомнительно

2024-04-01 18:53 UTC, CheerfulMushroom commented on public/components/Login/LoginView.js
> +        await this.checkAndSubmitForm();
Чего-то тут с асинхронностью каша: ты сделал асинхронный коллбэк на клик, чтобы сделать await на синхронную функцию :/

2024-04-01 18:53 UTC, CheerfulMushroom commented on public/components/Login/LoginView.js
> +        await this.checkAndSubmitForm();
Да и вообще в одну строчку можно хендлер повесить через bind и не придётся обертку из стрелочной функции делать

2024-04-01 18:53 UTC, CheerfulMushroom commented on public/components/Login/LoginView.js
> +  checkAndSubmitForm() {
Вот по использованию выше никто не читает возвращённое этой функцией значение, по JSDoc эта функция ничего не возвращает, а на самом деле зачем-то возвращает false в случае провала и undefined в случае успеха. Давай сделаем так, чтобы она ничего не возваращала

2024-04-01 20:32 UTC, kond9 commented on compileTemplates.sh
![image](https://github.com/frontend-park-mail-ru/2024_1_VKPogromisty/assets/91309407/882896f3-8651-44ee-abfa-2d895a0e78d5)

2024-04-01 22:05 UTC, CheerfulMushroom requested changes

2024-04-01 22:05 UTC, CheerfulMushroom commented on public/components/Login/LoginView.js
> +  checkAndSubmitForm() {
А теперь выходит, что ты на каждую проверку будешь в апи ходить. Прерывать выполнение надо, возвращать ничего не надо. Надо было просто вместо return false сделать return

2024-04-01 22:05 UTC, CheerfulMushroom commented on public/components/Login/LoginView.js
> +        await this.isValidForm();
У тебя тут функция синхронная, она по определению не будет выполняться параллельно. Нет смысла делать await, он только для асинхронных функций и промисов
https://learn.javascript.ru/async-await

2024-04-02 16:13 UTC, CheerfulMushroom approved these changes

2024-04-02 16:13 UTC, merged