VKP-83-profile-MVC: настроить профиль по MVC
frontend-park-mail-ru/2024_1_VKPogromisty pull request #28
Opened 2024-04-01 21:51 UTC by Famelbyby

2024-04-01 22:34 UTC, CheerfulMushroom requested changes
В целом всё круто, чисто на вопросики поотвечать и по своему желанию какие-то правки

2024-04-01 22:34 UTC, CheerfulMushroom commented on public/modules/services.js
> +        `?userId=${Number(userId)}&lastPostId=${Number(lastPostId)}`,
А если я userId передам, то я получу посты конкретного пользователя?

2024-04-01 22:34 UTC, CheerfulMushroom commented on public/modules/services.js
> +    const response = await fetch(this.baseUrl + "subscriptions", {
А чего такой жесткий адрес для ручки? subscriptions/subscriptions звучит криво

2024-04-01 22:34 UTC, CheerfulMushroom commented on public/modules/services.js
> +  async postSubscription(userId) {
JSDoc'а не хватает. Не понятно, что должны эти методы делать. Предположу, что подписать/отписать тебя от человека

2024-04-01 22:34 UTC, CheerfulMushroom commented on public/index.js
> +          console.log("yes");
лог

2024-04-01 22:34 UTC, CheerfulMushroom commented on public/components/Profile/ProfileView.js
> +   * @typedef {Object} Author
Слушай, а может стоит JSDoc тут в отдельный файл вынести? А то они просто нормально так места едят. Только надо проверить, что IDE всё ещё видит JSDoc и подсказки даёт по нему

Вот такое нашёл, но таким не занимался, какой будет результат хз. Вроде второй способ выглядит адекватно
https://stackoverflow.com/questions/43183450/jsdoc-typedef-in-a-separate-file

**ДЕЛАЙ НА СВОЁ УСМОТРЕНИЕ, МНЕ И ТАК ОК :)**

2024-04-01 22:34 UTC, CheerfulMushroom commented on public/components/Profile/ProfileView.js
А вьюха как-то будет отличатся визуально, если владелец просматривает свой профиль? Тип кнопки с удалением на постах там, или ещё чего?

2024-04-01 22:34 UTC, CheerfulMushroom commented on public/components/Profile/ProfileController.js
> +    this.eventBus.addEventListener(
Обычно контроллеры делают максимально тупыми и в них не содержат никакой логики. Событие logoutSuccess намекает на то, что этот контроллер как-то связан с логикой вью/модели, что кажется идейно кривовато.
Могу предложить что-нибудь из следующего: 
- передавать роутер вниз в модель и вью и пусть они творят с ним, что хотят
- завести какой-то специальный универсальный сигнал(ы) для редиректа (и не только) на путь
- какой-то другой третий и более богохульный вариант :)

Это так на будущее, сейчас править не надо, можно потом. Просто пометь где-нибудь, что стоит обратить на это внимание

2024-04-01 22:55 UTC, Famelbyby commented on public/modules/services.js
> +        `?userId=${Number(userId)}&lastPostId=${Number(lastPostId)}`,
Да) Можно и без преобразования через Number()

2024-04-01 22:56 UTC, Famelbyby commented on public/modules/services.js
> +    const response = await fetch(this.baseUrl + "subscriptions", {
Всё делается через swagger, указанный бэкендером)

2024-04-01 22:57 UTC, Famelbyby commented on public/components/Profile/ProfileView.js
1) Не будет кнопки подписаться/отписаться
2) Будет дисплей для создания постов
3) Будет возможность удалить/редактировать пост

2024-04-01 22:58 UTC, Famelbyby commented on public/components/Profile/ProfileController.js
> +    this.eventBus.addEventListener(
Придерживаюсь первого варианта, так как были мысли его реализовать

2024-04-01 23:06 UTC, Famelbyby commented on public/components/Profile/ProfileView.js
> +   * @typedef {Object} Author
Добавил

2024-04-02 07:02 UTC, CheerfulMushroom commented on public/modules/services.js
> +        `?userId=${Number(userId)}&lastPostId=${Number(lastPostId)}`,
А, всё, я почему-то подумал, что это страница самого пользователя, поэтому странным показалась, что надо userId передавать, чтобы свои же посты получить

2024-04-02 07:15 UTC, CheerfulMushroom commented on public/modules/services.js
> +    const response = await fetch(this.baseUrl + "subscriptions", {
Да, понимаю

2024-04-02 07:19 UTC, CheerfulMushroom commented on public/components/Profile/ProfileController.js
> +    this.eventBus.addEventListener(
Норм, довольно гибкий вариант

2024-04-02 07:48 UTC, CheerfulMushroom commented on public/components/Profile/profile.js
Блин, совсем просмотрел этот файл. Он используется где-то? Если нет и мы полностью перешли на mvc, то давай его выпилим

2024-04-02 07:48 UTC, CheerfulMushroom commented on public/components/Profile/ProfileView.js
> +   * @typedef {Object} Author
О, круть. IDE нормально распознаёт JSDoc, подсказки не потерялись?

2024-04-02 14:08 UTC, Famelbyby commented on public/components/Profile/profile.js
Насчёт следующего comment, а то я не могу отвечать там: да, IDE распознает все подсказки)

2024-04-02 15:26 UTC, CheerfulMushroom approved these changes

2024-04-02 15:27 UTC, merged