VKP-86-friends-MVC: настроить друзей по MVC
frontend-park-mail-ru/2024_1_VKPogromisty pull request #29
Opened 2024-04-03 12:41 UTC by Famelbyby

2024-04-03 19:08 UTC, CheerfulMushroom requested changes

2024-04-03 19:08 UTC, CheerfulMushroom commented on public/index.js
> +        func: friendsController.renderFriendsView.bind(friendsController),
Тут один контроллер три разные страницы рендерит?

2024-04-03 19:08 UTC, CheerfulMushroom commented on public/modules/dateRemaking.js
> +  return `${date.getDate().toString().padStart(2, "0")}.${(date.getMonth() + 1).toString().padStart(2, "0")}.${date.getFullYear()} в ${date.getHours().toString().padStart(2, "0")}:${date.getMinutes()
Надо бы это на несколько линий разбить, а то такое не прочитаешь. Предлагаю проинициализировать все нужные переменки (day, month...), а потом уже их в строку подставить

2024-04-03 19:08 UTC, CheerfulMushroom commented on public/components/Friends/FriendsView.js
> +/**
JSDoc лучше сразу после импортов. Как-то общепринято, что в начале скрипта всегда импорты

2024-04-03 19:08 UTC, CheerfulMushroom commented on public/components/Friends/FriendsController.js
> +class FriendsController {
На контроллер бы JSDoc, чтобы можно было сразу понять, за что конкретно он отвечает

2024-04-03 19:10 UTC, CheerfulMushroom commented on public/index.js
> +        func: friendsController.renderFriendsView.bind(friendsController),
Просто вся идея MVC - разбить код на малые части, чтобы было проще его читать, модифицировать и он не разрастался в большое полотно текста. А тут логика 3 страниц в одном mvc. Почему такое решение было принято?

2024-04-03 19:17 UTC, CheerfulMushroom commented on public/index.js
> +        func: friendsController.renderFriendsView.bind(friendsController),
Глянул макеты. Это просто 3 вкладки на одной странице?

2024-04-03 19:24 UTC, Famelbyby commented on public/index.js
> +        func: friendsController.renderFriendsView.bind(friendsController),
Да

2024-04-03 20:03 UTC, CheerfulMushroom requested changes

2024-04-03 20:03 UTC, CheerfulMushroom commented on public/components/Friends/FriendsController.js
> +    this.friendsModel.getOwnProfileData("friends");
Кажется, что рендер в контроллере должен дёргать рендер вью, чтобы оно могло что-то отрисовать сначала, а потом уже за данными начать идти. А то выйдет, что если у человека интернет медленный, то он нажмёт на вкладку, а там ничего не сменится следующие секунды 2. А так можно как-то ему будет показать, что загрузка данных началась с помощью какого-нибудь [лоадера](https://mui.com/material-ui/react-progress/) или [скелетона](https://mui.com/material-ui/react-skeleton/)

**МЕНЯТЬ НЕ НУЖНО, ПРОСТО НА ЗАМЕТКУ**

2024-04-03 20:03 UTC, CheerfulMushroom commented on public/components/Friends/FriendsController.js
> +    this.friendsModel.getOwnProfileData("subscribers");
Как-то некрасиво выходит: ты передаёшь эту строку, чтобы потом эта строка через getOwnProfileData попала во вью и была обработана там. Это часть логики отображения. То есть вышло так, что теперь у тебя часть логики из вью попало в контроллер, хотя контроллер у тебя должен быть максимально отвязанным от реализации и не должен знать, что там под капотом у него происходит.

Предлагаю сделать просто 3 метода для получения разных данных, которые уже будут дёргать getOwnProfileData с нужным path

2024-04-03 20:03 UTC, CheerfulMushroom commented on public/components/Friends/FriendsModel.js
> +    resultOwnProfile.body.User["path"] = path;
А почему так, а не `.path =`  ?

2024-04-04 06:43 UTC, CheerfulMushroom requested changes

2024-04-04 06:43 UTC, CheerfulMushroom commented on public/routes.js
> +  async updateUserState() {
Всё таки не должно состояние проекта лежать в роутере. У роутера есть чётко прописанная обязанность заниматься изменением путей. Хранение стейта приложения в неё не входит

2024-04-04 06:43 UTC, CheerfulMushroom commented on public/routes.js
> +  async updateUserState() {
Могу предложить такой подход:
- Создаём класс стейта приложения
- Инициализируем его перед контроллерами
- Передаём его в контроллеры для их дальнейшего использования в моделях/вьюхах

2024-04-04 06:43 UTC, CheerfulMushroom commented on public/components/Signup/SignupModel.js
> +        this.router.updateUserState();
Потенциальный race condition:
Ты вызвал обновление состояния и начал рендерить следующую страницу. Если состояние не успеет обновиться или там будут проблемы, то стейт останется пустым у следующих страниц, которые полагаются на актуальность состояния, будут проблемы


Нужно дождаться ответа, обработать его и, может, сказать что-то пользователю в случае ошибки

2024-04-04 17:07 UTC, CheerfulMushroom requested changes
Вроде все ок, финально гляну ещё раз через часа 3. Пока последний раз пройтись по правкам

2024-04-04 17:07 UTC, CheerfulMushroom commented on public/components/Friends/FriendsView.js
> +   * @param {Friend} friends
А тут не массив должен быть? Глянь, типы в jsdoc'ах ещё раз на всякий случай

2024-04-04 17:07 UTC, CheerfulMushroom commented on public/index.js
> +          await userState.updateState();
Тут по-хорошему тоже стоит результат проверять

2024-04-04 17:07 UTC, CheerfulMushroom commented on public/index.js
> +          await userState.updateState();
Слушай, раз запрос не придёт, если пользователь не авторизован, может есть смысл избавиться тут от ручки isAithorized и смотреть тут результат получения данных о самом пользователе?

2024-04-04 20:15 UTC, CheerfulMushroom requested changes

2024-04-04 20:15 UTC, CheerfulMushroom commented on public/index.js
>    document.addEventListener("navigate", route);
Событие navigate - штука супер свежая и не все последние браузер про неё знают (по факту только хром)
https://caniuse.com/?search=navigate

Собственно зачем на неё повесили обработчик изначально? Кажется, что этот обработчик будет вызываться на любое изменение адреса, что избыточно. У вас обработкой переходов должен заниматься роутре, а не обработчик route

Могу предположить, что изначально это задумывалось как способ на старте приложения определить, какой коллбэк вызвать, так?

2024-04-04 20:15 UTC, CheerfulMushroom commented on public/index.js
>    document.addEventListener("navigate", route);
Функция route очень сильно полагается на то, что isAuthorized успеет стать актуальным. По идее ещё один потенциальный race condition

2024-04-04 20:17 UTC, Famelbyby commented on public/index.js
>    document.addEventListener("navigate", route);
К сожалению эту часть кода писал не я, просто работало и пусть работает, но сейчас будет исправлено)

2024-04-04 20:26 UTC, CheerfulMushroom approved these changes

2024-04-04 20:26 UTC, merged