VKP-90-refactor: добавить CSRFProtection, сделать UserState синглтоном
frontend-park-mail-ru/2024_1_VKPogromisty pull request #34
Opened 2024-04-13 18:31 UTC by Famelbyby

2024-04-13 18:53 UTC, CheerfulMushroom requested changes

2024-04-13 18:53 UTC, CheerfulMushroom commented on public/components/Signup/SingupView.js
> +      if (validExtensions.indexOf(typeFile) === -1) {
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

2024-04-13 18:53 UTC, CheerfulMushroom commented on public/components/Signup/SingupView.js
> +      if (!validateEmail(email.value.trim())) {
Кажется, что trim стоит убрать непосредственно в validate

2024-04-13 18:53 UTC, CheerfulMushroom commented on public/routes.js
> +    document.onscroll = null;
А это зачем?

2024-04-13 18:53 UTC, CheerfulMushroom commented on public/components/CSRFProtection.js
> +    return await fetch(url, state);
Кажется, тут await не нужен

2024-04-13 18:53 UTC, CheerfulMushroom commented on public/components/CSRFProtection.js
> +class CSRFProtection {
Синглтон - это когда ты делаешь несколько new Class и они возвращают одну и ту же ссылку. Но тут это не нужно, и так норм

2024-04-13 18:55 UTC, CheerfulMushroom requested changes

2024-04-13 18:55 UTC, CheerfulMushroom commented on public/modules/services.js
> +    const response = await CSRFProtection(this.baseUrl, {
Не потерял addCSRFToken ?

2024-04-13 19:02 UTC, Famelbyby commented on public/routes.js
> +    document.onscroll = null;
Если так не делать, то при прокрутке на страницах, отличных от feed/profile будут кидаться запросы постов на сервер

2024-04-13 23:26 UTC, CheerfulMushroom commented on public/routes.js
> +    document.onscroll = null;
Потому что не подчищаешь за собой листенеры после лент. У каждой view должен быть метод для очистки за собой, который должен вызываться, когда view собираются удалить

2024-04-13 23:29 UTC, CheerfulMushroom requested changes

2024-04-13 23:29 UTC, CheerfulMushroom commented on dist/chat.bundle.js
Все бандлы в гитигнор

2024-04-13 23:29 UTC, CheerfulMushroom commented on dist/chat.bundle.js
И вообще всю сборку туда же

2024-04-13 23:33 UTC, CheerfulMushroom requested changes

2024-04-13 23:33 UTC, CheerfulMushroom commented on dist/index.html
Не очень понял, почему index.html переехал в dist

2024-04-13 23:33 UTC, CheerfulMushroom commented on dist/index.html
Вебпак ещё не доделан. Весь проект должен автоматически собираться в один index.js, index.css и index.html файлы и класться в папку dist
Handlebars тоже должен собираться теперь вебпаком, а не скриптом нашим

В идеале должно быть так, чтобы я мог склонить проект, сделать npm i, npm run build и получить папку с собранным проектом

2024-04-13 23:36 UTC, CheerfulMushroom requested changes

2024-04-13 23:36 UTC, CheerfulMushroom commented on package.json
> +    "(?!.*(dist))*.{js,jsx,ts,tsx,html,css,hbs}": "prettier --write",
Добавляй dist в gitignore и откатывай это

2024-04-13 23:36 UTC, CheerfulMushroom commented on webpack.config.js
> +    index: './public/index.js',
Одна точка входа должна быть для сборки проекта

2024-04-14 11:27 UTC, CheerfulMushroom requested changes
1) Index.html точно не нужен для сборки проекта?
2) Проверь, что всё норм собирается: склонь куда-нибудь эту репу, выполни `npm i && npm run build` 
Если проблем нет, то в dist должна после этого появится вся сборка

2024-04-14 11:27 UTC, CheerfulMushroom commented on package.json
> +  "private": "true",
Не излишне будет?

2024-04-15 11:10 UTC, CheerfulMushroom approved these changes

2024-04-15 11:10 UTC, merged