VKP-65-offline: сделать оффлайн для GET-запросов
frontend-park-mail-ru/2024_1_VKPogromisty pull request #37
Opened 2024-04-19 14:38 UTC by Famelbyby

2024-04-19 14:59 UTC, CheerfulMushroom requested changes

2024-04-19 14:59 UTC, CheerfulMushroom commented on public/index.js
> +      .register()
Судя по доке ты должен сюда передавать ссылку на скрипт сервис воркера
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/register

2024-04-19 14:59 UTC, CheerfulMushroom commented on public/index.js
> +      .then(() => {})
Если then ничего не делает, то он тут как будто не нужен

2024-04-19 14:59 UTC, CheerfulMushroom commented on public/index.js
> +        console.log("Registration failed with " + error);
Если это реально нужная ошибка в консоли, то делай console.error вместо log и убирай волшебный коммент выше

2024-04-19 14:59 UTC, CheerfulMushroom commented on public/sw.js
> +              console.log(e);
console.error

2024-04-19 14:59 UTC, CheerfulMushroom commented on .gitignore
> +serviceworker-webpack5-plugin
А это зачем? o_o
Там где-то такая папка/файл создаются?

2024-04-19 14:59 UTC, CheerfulMushroom commented on package.json
> +    "serviceworker-webpack-plugin": "^1.0.1",
Так как как ты используешь этот плагин, то расскажи тут, зачем он и что делает)

2024-04-19 18:29 UTC, Famelbyby commented on package.json
> +    "serviceworker-webpack-plugin": "^1.0.1",
Это плагин, который позволяет добавить в глобальную переменную serviceWorkerOption['assets'] имена всех файлов, которые будут в рабочей папке /dist и которые нужны для добавления в cache. Коротко говоря, он упрощает добавление файлов для кеша, автоматизируя работу

2024-04-20 12:54 UTC, CheerfulMushroom approved these changes

2024-04-20 12:54 UTC, merged