Create authorization page
frontend-park-mail-ru/2024_1_VKPogromisty pull request #4
Opened 2024-02-29 15:14 UTC by kond9

2024-02-29 18:15 UTC, CheerfulMushroom requested changes

2024-02-29 18:15 UTC, CheerfulMushroom commented on Logo.png
Давай немного файловую структурe в проекте организуем
- /static - вся статика (файлы, которые будет отдаваться пользователю "как есть") будет лежать в папке 
- /static/images/ - папка для изображений (заглушки, логотипы, какие-нибудь иконки, картинки для лендинга)

То есть сейчас html и css надо закинуть в /static, а лого в /static/images/

2024-02-29 18:15 UTC, CheerfulMushroom commented on styles.css
Стоит переименовать файл в authorization.css

2024-02-29 18:15 UTC, CheerfulMushroom commented on authorization.html
> +        <link rel="stylesheet" href="styles.css" />
Как ты уже мог почувствовать, тебе при вёрстке могли помешать встроенные в браузер по умолчанию стили. Например, я вижу, что ты в body добавил margin: 0. Причём у разных браузеров стили могут быть разные :)

Для того, чтобы сбрасывать эти стили был придуман reset.css и его идеологические последователи в форме normalize.css и кучки других "сбрасывателей". По факту это файлы стилей, которые за тебя обнуляют и приводят в норму все дефолтные стили.

Собственно задача: найти в интернете и добавить файл reset.css и подключить его перед твоими стилями

2024-02-29 18:15 UTC, CheerfulMushroom commented on styles.css
> +    margin: 0;
Как подключишь reset.css, убери все свои сбросы

2024-02-29 18:15 UTC, CheerfulMushroom commented on styles.css
> +    height: 100vh;
Вот тут есть проблема: если сжать страницу по высоте, то форма уедет и скроллов не будет

2024-02-29 18:15 UTC, CheerfulMushroom commented on styles.css
> +  margin: 0 auto;
отступ

2024-02-29 18:15 UTC, CheerfulMushroom commented on styles.css
> +    background-color: #fceeeb;
Я не уверен, но визуально кажется, что цвет инпута совпадает с цветом фона. Может тогда один и тот же цвет использовать?

2024-02-29 18:15 UTC, CheerfulMushroom commented on styles.css
> +    background: rgba(235, 158, 158, 0.23);
Давай все специфичные цвета выносить в глобальные css переменны (см https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)

2024-02-29 18:15 UTC, CheerfulMushroom commented on styles.css
> +    background: rgba(254, 201, 201);
Здесь висит тот же цвет, что и в обычной кнопке. Так запланировано?

2024-02-29 18:15 UTC, CheerfulMushroom commented on styles.css
> +    padding: 20px;
А зачем тут паддинг? Что сломается, если его убрать?

2024-02-29 18:15 UTC, CheerfulMushroom commented on styles.css
> +button {
Смотри, если ты накидываешь свойства с таким селектором, то ты утверждаешь, что эти свойства должны быть у всех кнопок в проекте. Я сомневаюсь, что так будет. Убери все эти свойства в отдельный класс и навесь его на кнопку

2024-02-29 18:15 UTC, CheerfulMushroom commented on authorization.html
Контент помещается, а скролл непонятно откуда взялся

![image](https://github.com/frontend-park-mail-ru/2024_1_VKPogromisty/assets/43929910/c1e4d615-cee4-4dae-8074-9cf7195929b9)

2024-02-29 18:15 UTC, CheerfulMushroom commented on authorization.html
А тут не помещается по горизонтали, а в самом левом положении скролла не видно левой стороны формы
![image](https://github.com/frontend-park-mail-ru/2024_1_VKPogromisty/assets/43929910/fd21c5e0-a7aa-48df-8038-d00fd6e011d8)

2024-02-29 20:07 UTC, kond9 commented on Logo.png
Сделал

2024-02-29 20:07 UTC, kond9 commented on styles.css
Сделал

2024-02-29 20:16 UTC, kond9 commented on authorization.html
> +        <link rel="stylesheet" href="styles.css" />
Сделал

2024-02-29 20:25 UTC, kond9 commented on styles.css
> +    margin: 0;
Сделал (в reset уже всё написано и не нужно повторять)

2024-02-29 20:52 UTC, kond9 commented on styles.css
> +    height: 100vh;
изменил height на min-height, чтобы занималось всё пространство браузера и элементы не отъезжали

2024-02-29 20:54 UTC, kond9 commented on styles.css
> +  margin: 0 auto;
Сделано

2024-02-29 20:56 UTC, kond9 commented on styles.css
> +    background-color: #fceeeb;
Это не один и тот же цвет. Схожие, но не одинаковые (отталкивался от цветов в figma)

2024-02-29 21:10 UTC, kond9 commented on styles.css
> +    background: rgba(235, 158, 158, 0.23);
Сделал

2024-02-29 21:12 UTC, kond9 commented on styles.css
> +    background: rgba(254, 201, 201);
Так не запланировано, просто мы такой момент не обсуждали пока что)

2024-02-29 21:16 UTC, kond9 commented on authorization.html
Исправил

2024-02-29 21:17 UTC, kond9 commented on authorization.html
Исправил

2024-02-29 21:23 UTC, kond9 commented on styles.css
> +button {
Исправил, переделал в класс button-sign-in

2024-02-29 21:27 UTC, kond9 commented on styles.css
> +    padding: 20px;
Паддинг здесь для того, чтобы контент страницы не был прижат к краям экрана. Соответственн, если уберём, сам body станет больше, прижавшись к экрану

2024-02-29 21:51 UTC, CheerfulMushroom commented on styles.css
> +    padding: 20px;
Всё-таки не очень правильно его на body вешать. Если ты его так повесишь, то как будешь потом добавлять в body хедер, который должен быть прижат к верху?

2024-02-29 21:56 UTC, kond9 commented on styles.css
> +    padding: 20px;
Убрал его из body

2024-02-29 22:04 UTC, CheerfulMushroom requested changes

2024-02-29 22:04 UTC, CheerfulMushroom commented on static/reset.css
> +html {overflow-y: scroll;}
Очень сомнительный reset.css возьми другой

2024-02-29 22:04 UTC, CheerfulMushroom commented on static/authorization.css
> +    min-width: 100vh;
Ну это точно неправильно. Как минимум тут vh для ширины использовать сомнительная идея

2024-03-02 20:29 UTC, CheerfulMushroom approved these changes

2024-03-02 20:29 UTC, merged