VKP-129-comments: добавить комментарии
frontend-park-mail-ru/2024_1_VKPogromisty pull request #49
Opened 2024-05-15 19:16 UTC by Famelbyby

2024-05-15 21:01 UTC, CheerfulMushroom requested changes

2024-05-15 21:01 UTC, CheerfulMushroom commented on public/components/Admin/AdminView.js
Радикально

2024-05-15 21:01 UTC, CheerfulMushroom commented on public/components/Signup/SingupView.js
> +      if (!validExtensions.includes(typeFile) || file.size / MBToByte > 5) {
А юзер сможет понять, что ошибка произошла из-за размера картинки?

2024-05-15 21:01 UTC, CheerfulMushroom commented on public/components/createComponent.js
> +export function buildComponent(tagName, attrs, classes, innerHTML) {
Кажется, что если бы attrs были объектом, то код, где используется buildComponent, было бы читать значительно легче

2024-05-15 21:01 UTC, CheerfulMushroom commented on public/components/Friends/FriendsView.js
> +  addHrefing() {
А зачем так сложно? Почему просто `<a>` не использовать?

2024-05-15 21:01 UTC, CheerfulMushroom commented on public/components/Friends/FriendsView.js
> +  addHrefing() {
Причём по шаблону вижу, что раньше так и было. Зачем убрал?

2024-05-15 21:01 UTC, CheerfulMushroom commented on public/components/Group/GroupView.js
> +      if (!validExtensions.includes(typeFile) || file.size / MBToByte > 5) {
Пользователю покажут причину?

2024-05-15 21:01 UTC, CheerfulMushroom commented on public/components/Post/post.scss
Чего-то так много по комментарию добавилось, что хочется в отдельный компонент вынести

2024-05-15 21:01 UTC, CheerfulMushroom commented on public/components/Settings/SettingsView.js
> +      if (!validExtensions.includes(typeFile) || file.size / MBToByte > 5) {
Тоже самое, как-то пользователь ошибку поймёт?

2024-05-15 21:01 UTC, CheerfulMushroom commented on public/components/Post/PostView.js
> +    appendChildren(postAuthor, [
На это прямо очень больно смотреть, весь шаблон во вью вынесен, как я понял. Оно из-за этого разрослось до каких-то абсурдных размеров. Давай хотя бы по разным js файлам это разнесём

2024-05-15 21:01 UTC, CheerfulMushroom commented on public/components/Post/PostView.js
> +    appendChildren(postAuthor, [
Ну и пока без всё ещё сомнения есть по поводу такого подхода, давай потом созвонимся и покажешь, что от этого лучше стало

2024-05-15 21:47 UTC, Famelbyby commented on public/components/Friends/FriendsView.js
> +  addHrefing() {
Сказали переделать, чтобы была большая область нажатия пальчиком)

2024-05-21 08:32 UTC, CheerfulMushroom approved these changes

2024-05-21 08:32 UTC, merged