VKP-25-registration: сделать вёрстку сайта с регистрацией для будущей регистрации пользователей
frontend-park-mail-ru/2024_1_VKPogromisty pull request #5
Opened 2024-02-29 21:40 UTC by Famelbyby

2024-03-01 20:23 UTC, CheerfulMushroom requested changes

2024-03-01 20:23 UTC, CheerfulMushroom commented on static/styles/sign_up.css
> +}
Переносы строк в конце файлов

2024-03-01 20:23 UTC, CheerfulMushroom commented on templates/sign_up.html
> +                    <input class="main-input" type="text" name="last_name" placeholder="Last name" required><br>
Не надо использовать br для организации верстки, используй flex

2024-03-01 20:23 UTC, CheerfulMushroom commented on static/styles/sign_up.css
> +    font-family: var(--page-font-family);
Шрифт есть смысл перенести в body. У вас всё равно больше одного шрифта не будет

2024-03-01 20:23 UTC, CheerfulMushroom commented on static/styles/reset.css
Откуда брал reset.css?

2024-03-01 20:23 UTC, CheerfulMushroom commented on templates/sign_up.html
> +                            <span>Upload</span>
"Upload avatar" может? В макетах так написано

2024-03-01 20:23 UTC, CheerfulMushroom commented on static/styles/reset.css
> +	cursor: pointer;
Какой-то он совсем кривой, такого быть не должно. С чего все label'ы должны иметь cursor: pointer

2024-03-01 20:23 UTC, CheerfulMushroom commented on static/styles/reset.css
> +	cursor: pointer;
Возьми отсюда reset.css
https://gist.github.com/DavidWells/18e73022e723037a50d6

2024-03-01 20:23 UTC, CheerfulMushroom commented on static/styles/sign_up.css
> +    background-color: rgb(248,238,238)
Это один из основных цветов в приложении, его есть смысл перенести в переменную

2024-03-01 20:23 UTC, CheerfulMushroom commented on templates/sign_up.html
> +        <meta name="viewport" content="width=device-width, initial-scale=1">
Сможешь обосновать, зачем это нужно?

2024-03-01 20:23 UTC, CheerfulMushroom commented on templates/sign_up.html
> +                    <label for="date-birthday" class="form-label">Date of birthday</label><br>
![image](https://github.com/frontend-park-mail-ru/2024_1_VKPogromisty/assets/43929910/f01e7bcd-d4d0-4e2d-aa06-f860a76ba8c0)

2024-03-01 20:23 UTC, CheerfulMushroom commented on templates/sign_up.html
> +        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
Подключи шрифт в стили через import

2024-03-01 20:23 UTC, CheerfulMushroom commented on templates/sign_up.html
> +        <main>
Почему main, а не просто div?

2024-03-01 20:23 UTC, CheerfulMushroom commented on templates/sign_up.html
> +                        <input id="day" type="number" min="1" required placeholder="DD">
Надо от этих стрелочек избавиться, выглядят не оч
![image](https://github.com/frontend-park-mail-ru/2024_1_VKPogromisty/assets/43929910/5e74d7e0-3af2-4911-9308-9cc16e79a647)

2024-03-01 20:23 UTC, CheerfulMushroom commented on templates/sign_up.html
> +                        <label class="input-avatar">
Label меньше своего контента. Когда ребенок неожиданно вылезает за пределы родителя - это признак того, что в вёрстке что-то пошло не так, и эта проблема скоро станет источником головных болей. Вижу, что ты уже маргинов накидал на соседние кнопки, чтобы они друг с другом не пересекались

Чинится добавлением буквально одного свойства на одного из детей label

![image](https://github.com/frontend-park-mail-ru/2024_1_VKPogromisty/assets/43929910/2863de40-c4d7-40d6-b461-79b3be8a050f)

2024-03-01 20:23 UTC, CheerfulMushroom commented on templates/sign_up.html
> +                    <input class="main-input" type="text" name="last_name" placeholder="Last name" required><br>
https://web.dev/learn/css/flexbox

2024-03-01 20:23 UTC, CheerfulMushroom commented on templates/sign_up.html
> +                        <label class="input-avatar">
https://web.dev/learn/css/layout

2024-03-01 20:23 UTC, CheerfulMushroom commented on templates/sign_up.html
> +                            <span>Upload</span>
А, вы макеты на русский начали переводить только что :)

2024-03-02 14:30 UTC, CheerfulMushroom commented on templates/sign_up.html
> +        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
Отбой, я прочитал, что лучше так, как предлагает гугл. Но всё равно надо будет понимать, почему лучше так, а не через import и зачем нужны link preconnect

2024-03-02 21:08 UTC, kond9 commented on static/styles/sign_up.css
> +}
сделал

2024-03-02 21:17 UTC, kond9 commented on templates/sign_up.html
> +        <main>
Сделал

2024-03-02 21:20 UTC, kond9 commented on templates/sign_up.html
> +                        <input id="day" type="number" min="1" required placeholder="DD">
Сделал

2024-03-02 21:21 UTC, kond9 commented on static/styles/reset.css
> +	cursor: pointer;
Сделал

2024-03-02 21:39 UTC, kond9 commented on static/styles/sign_up.css
> +    background-color: rgb(248,238,238)
Сделал

2024-03-02 21:42 UTC, kond9 commented on static/styles/sign_up.css
> +    font-family: var(--page-font-family);
Сделал

2024-03-02 22:21 UTC, kond9 commented on templates/sign_up.html
> +                    <input class="main-input" type="text" name="last_name" placeholder="Last name" required><br>
Сделал

2024-03-03 12:45 UTC, CheerfulMushroom commented on templates/sign_up.html
> +                    <label for="date-birthday" class="form-label">Date of birthday</label><br>
Актуально, нужно потом починить

2024-03-03 12:48 UTC, CheerfulMushroom commented on templates/sign_up.html
> +                        <label class="input-avatar">
Подбирать маргины - плохое решение. Потом нужно будет почнить

2024-03-03 12:48 UTC, CheerfulMushroom approved these changes

2024-03-03 12:48 UTC, merged