VKP-24-feed: создать вёрстку сайта ленты для будущей возможности пользователя просматривать новости
frontend-park-mail-ru/2024_1_VKPogromisty pull request #6
Opened 2024-03-01 11:54 UTC by Famelbyby

2024-03-01 21:07 UTC, CheerfulMushroom requested changes

2024-03-01 21:07 UTC, CheerfulMushroom commented on static/images/commenting-svgrepo-com.svg
Давай картинкам дадим более понятные имена вместо названий сайтов. icon-heart.svg, icon-msg.svg. Что-то типа

2024-03-01 21:07 UTC, CheerfulMushroom commented on templates/feed.html
> +          <button class="include-button"><svg class="include" fill="#858080" width="16px" height="16px" viewBox="-4.5 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="m9.818 0c-3.012 0-5.455 2.44
Это выглядит больно, конечно. Почему просто img с ссылкой на svg?

2024-03-01 21:07 UTC, CheerfulMushroom commented on templates/feed.html
> +        <li><a href="">Профиль</a></li>
Обычно # втыкают в href в качестве заглушок. Так при нажатии на ссылку страница не обновляется

2024-03-01 21:07 UTC, CheerfulMushroom commented on templates/feed.html
> +  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
Подключи шрифт в стили через import, а не через html

2024-03-01 21:07 UTC, CheerfulMushroom commented on templates/feed.html
> +  <link href="https://fonts.googleapis.com/css2?family=Jim+Nightshade&display=swap" rel="stylesheet">
Я, конечно, не сомневаюсь, что вы крутые, но не на столько, чтобы удачно использовать 2 шрифта в проекте. Оставьте только один и сделайте его основным

2024-03-01 21:07 UTC, CheerfulMushroom commented on templates/feed.html
> +      <div class="logo">ocio</div>
Не, давайте одну картинку оставим. Смешивание лого с текстом выглядит не очень красиво

2024-03-01 21:07 UTC, CheerfulMushroom commented on static/styles/sign_up.css
Кажется, что этих файлов быть в этом ПР не должно

2024-03-01 21:07 UTC, CheerfulMushroom commented on static/styles/feed.css
> +}
Перенос строки в конце

2024-03-01 21:07 UTC, CheerfulMushroom commented on templates/feed.html
Контент не отцентрирован по горизонтали
![image](https://github.com/frontend-park-mail-ru/2024_1_VKPogromisty/assets/43929910/384d3d41-bef8-4044-a6ce-2dee9b23174f)

2024-03-01 21:07 UTC, CheerfulMushroom commented on templates/feed.html
> +  <link href="https://fonts.googleapis.com/css2?family=Jim+Nightshade&display=swap" rel="stylesheet">
Увидел, это в логотипе используется. Давайте вырежем и только лого оставим. Картинка с текстом не оч сочетается, просто лого будет лаконичнее смотреться

2024-03-01 21:07 UTC, CheerfulMushroom commented on templates/feed.html
![image](https://github.com/frontend-park-mail-ru/2024_1_VKPogromisty/assets/43929910/c66beefc-4890-491c-b01f-802102858e37)

2024-03-01 21:07 UTC, CheerfulMushroom commented on templates/feed.html
Там чего-то все посты кроме первого выглядят слегка кривовато

2024-03-01 21:07 UTC, CheerfulMushroom commented on templates/feed.html
> +          <button class="include-button"><svg class="include" fill="#858080" width="16px" height="16px" viewBox="-4.5 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="m9.818 0c-3.012 0-5.455 2.44
Вижу, что тут накидывается цвет и вращение. Лучше один раз просто картинку отредачить как надо. Всё равно вы не будете использовать их оригиналы

2024-03-01 21:07 UTC, CheerfulMushroom commented on templates/feed.html
> +          <button class="include-button"><svg class="include" fill="#858080" width="16px" height="16px" viewBox="-4.5 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="m9.818 0c-3.012 0-5.455 2.44
Или сразу нормальные скачайте. Можно даже в png, никто их на весь экран растягивать не будет

https://www.flaticon.com/free-icons/attached
https://www.flaticon.com/free-icons/send

2024-03-01 21:07 UTC, CheerfulMushroom commented on templates/feed.html
Не надо центровать текст по вертикали через маргины, это костыльно. Flexbox в помощь

![image](https://github.com/frontend-park-mail-ru/2024_1_VKPogromisty/assets/43929910/6e99746d-2151-4332-ab74-370978fbe769)

2024-03-01 21:07 UTC, CheerfulMushroom commented on static/styles/feed.css
> +    min-width: 200px;
2 раза одно и то же свойство прописал.
Вообще, выглядит костыльно. Было бы логично, если бы эта часть сама занимала бы всё доступное место в родительском flex. Более того, flex такое умеет)

Так что выпиливай эти 3 явно заданные ширины и замени их на одно волшебное flex свойство (но какое не скажу 🙃)

2024-03-01 21:07 UTC, CheerfulMushroom commented on templates/feed.html
Надо убедиться, что всё, что должно тыкаться пользователем, является ссылкой или на нём висит cursor, как у ссылки. Иначе выглядит так, что на это кликнуть нельзя.
Из того, что я увидел:
- логотип
- троеточия
- имя пользователя
- аватарки с именами в постаъ и комментариях

2024-03-02 14:30 UTC, CheerfulMushroom commented on templates/feed.html
> +  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
Отбой, я прочитал, что лучше так, как предлагает гугл. Но всё равно надо будет понимать, почему лучше так, а не через import и зачем нужны link preconnect

2024-03-03 14:09 UTC, kond9 commented on static/images/commenting-svgrepo-com.svg
Сделал

2024-03-03 20:00 UTC, CheerfulMushroom requested changes

2024-03-03 20:00 UTC, CheerfulMushroom commented on templates/feed.html
Курсор не grub должен быть, а pointer

2024-03-03 20:00 UTC, CheerfulMushroom commented on templates/feed.html
> +                                    class="user-avatar-post"
Кажется, что этого класса здесь быть не должно, у кнопки обводка появилась
![image](https://github.com/frontend-park-mail-ru/2024_1_VKPogromisty/assets/43929910/b1f4cb31-fda1-4439-b928-97adc4a9690c)

2024-03-03 20:00 UTC, CheerfulMushroom commented on static/styles/feed.css
> +    padding-top: 6px;
Тут что-то страшное и не отцентрированное

![image](https://github.com/frontend-park-mail-ru/2024_1_VKPogromisty/assets/43929910/e1af1a94-bb22-445a-bb46-9032ffecbb32)

2024-03-03 20:00 UTC, CheerfulMushroom commented on static/styles/feed.css
> +    transform: rotate(25deg);
Вроде как неактуально теперь, раз иконки все нормальные

2024-03-03 20:37 UTC, CheerfulMushroom approved these changes

2024-03-03 20:53 UTC, merged